config/routes.rb
sk_route = '/sidekiq/' + ENV['SIDEKIQ_SECRET']

Doorman::Application.routes.draw do

  require 'sidekiq/web'

  mount Sidekiq::Web => sk_route

  get "dashboard/index"

  devise_for :users

  get 'welcome/index'

  root :to => 'welcome#index'

  get '/dashboard', to: 'dashboard#index'

  post '/voice/incoming', to: 'voice#incoming'
  post '/voice/settings_test', to: 'voice#settings_test'

  get '/settings/create_twilio_account', to: 'settings#create_twilio_account'
  get '/settings/fetch_twilio_number', to: 'settings#fetch_twilio_number'
  get '/settings/buy_twilio_number', to: 'settings#buy_twilio_number'
  get '/settings/test_settings', to: 'settings#test_settings'
  get '/settings/start_timer', to: 'settings#start_timer'
  get '/settings/update_mode', to: 'settings#update_mode'

  resources :settings

  match '*path' => redirect('/')

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doorman</title>
  <%= favicon_link_tag '/favicon.png', type: 'image/png' %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "jumbotron-narrow", :media => "all" %>
  <link href='https://fonts.googleapis.com/css?family=Coustard' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="header">
      <ul class="nav nav-pills pull-right">

        <% if user_signed_in? %>
          <% if current_user.setting %>
          <!-- Checks to see if user completed initial setup  -->
            <li><%= link_to "Dashboard", dashboard_path %></li>
            <li><%= link_to "Settings", edit_setting_path(current_user.setting.id) %></li>
            <li><%= link_to "Profile", edit_user_registration_path %></li>
            <li class="active"><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>

          <% else %>
            <li><%= link_to "Dashboard", dashboard_path %></li>
            <li><%= link_to "Settings", new_setting_path %></li>
            <li><%= link_to "Profile", edit_user_registration_path %></li>
            <li class="active"><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% end %>


        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
        <% if current_page?('/') == false  %>
          <h3><a href="/" class="logolink"><i class="fa fa-lock"></i> <span class="logo">Doorman</span></h3></a>
        <% end %>

    </div>

  <% if notice || alert %>
    <div class="alert alert-warning fade in">
      <div id="flash">
        <%= notice %>
        <%= alert %>
      </div>
    </div>
  <% end %>

  <%= yield %>

<!-- Modal -->
<div class="modal fade" id="aboutModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">About Doorman</h4>
      </div>
      <div class="modal-body">

        <p>Doorman was built during General Assembly's <%= link_to "Web Development Immersive", "http://generalassemb.ly/education/web-development-immersive" %> using Ruby on Rails, Devise, PostgreSQL, jQuery, CoffeeScript, Bootstrap, Sidekiq, and Unicorn.</p>

        <div class="media">
          <a class="pull-left" href="https://github.com/zestos">
            <%= image_tag("luke.jpg", class: "media-object img-rounded", height: "64", width: "64", alt: "Luke Whiting") %>
          </a>
          <div class="media-body">
            <h4 class="media-heading">Luke Whiting</h4>
            <a href="http://lukewhiting.com" target="_blank">Blog</a> |
            <a href="http://github.com/zestos" target="_blank">Github</a> |
            <a href="http://linkedin.com/in/lukewhiting" target="_blank">LinkedIn</a> |
            <a href="http://twitter.com/zestos20" target="_blank">Twitter</a>
          </div>
        </div>

      </div>
      <div class="modal-footer">
        <span class="pull-left">&#169; 2013</span>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

    <div class="footer">
      <% if user_signed_in? %>
        <a id="about-link" href="#">About</a> | logged in as <strong><%= link_to current_user.email, edit_user_registration_path %></strong>
      <% else %>
        <a id="about-link" href="#">About</a>
      <% end %>
    </div>
  </div>

</body>
</html>